# Aaron Fienberg
#
# Check ADC test patterns for data capture errors
#
# Error counts assume that the first sample is correct
#

import stf
from iceboot import iceboot_session
from iceboot.ads4149 import setRegister as setADCRegister
from iceboot.ads4149 import ADS_4149_TP_REG
from iceboot.test_waveform import parseTestWaveform
from DEggTest.fpga_reg import fpga_write
import numpy as np


@stf.measures(stf.M('n_sample_errors').equals(0))
def run_test(test, session, channel,
             wfm_period=2, wfm_len=1000, n_waveforms=800):
    '''this test checks for ADC bit errors using 
    test patterns generated by the ADS4149 chip'''
    total_sample_errors = 0

    for pat_name in ['Ones', 'Zeroes', 'Ramp', 'Toggle']:
        pattern_errors = check_test_pat(session, channel, pat_name,
                                        wfm_period, wfm_len, n_waveforms)

        test.logger.info(f'{pattern_errors} errors reading {pat_name} '
                         f'pattern from channel {channel}')

        total_sample_errors += pattern_errors

    test.logger.info(f'{total_sample_errors} total errors '
                     'from channel {channel}')
    test.measurements.n_sample_errors = total_sample_errors


stf.register(
    version='1.0',
    test_name='ADCTestPatterns',
    run=run_test,
)


def count_one_errors(samples):
    return np.count_nonzero(samples - 0x3fff)


def count_zero_errors(samples):
    return np.count_nonzero(samples)


def count_ramp_errors(samples):
    expected = np.remainder(
        np.arange(samples.size) + samples[0], 1 << 14)

    return np.count_nonzero(samples - expected)


def count_toggle_errors(samples):
    even_val = samples[0]
    odd_val = (~samples[0]) & 0x3fff

    toggle_pat = 0x2aaa

    # check that either the first or second sample is 0x2aaa
    # if not, report that every sample is wrong
    if even_val != toggle_pat and odd_val != toggle_pat:
        return samples.size

    expected = np.empty_like(samples)
    expected[::2] = even_val
    expected[1::2] = odd_val

    return np.count_nonzero(samples - expected)


ERR_COUNT_FUNC_MAP = {
    'Ones': count_one_errors,
    'Zeroes': count_zero_errors,
    'Ramp': count_ramp_errors,
    'Toggle': count_toggle_errors
}


def check_test_pat(session, channel, pat_name,
                   wfm_period=2, wfm_len=1000, n_waveforms=1000):
    setADCRegister(session, ADS_4149_TP_REG, pat_name, channel)

    count_sample_errors = ERR_COUNT_FUNC_MAP[pat_name]

    fpga_write(session, f'test_conf[{channel}]', int(wfm_len//4))

    n_bit_errors = 0

    session.startDEggSWTrigStream(channel, wfm_period)
    for _ in range(n_waveforms):
        wfm = parseTestWaveform(session.readWFMFromStream())

        if wfm['channel'] != channel:
            raise RuntimeError('Read a waveform from the wrong channel!')

        n_bit_errors += count_sample_errors(wfm['waveform'])

    session.endStream()

    return n_bit_errors


if __name__ == '__main__':
    stf.run()
